version: "3.9"

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: portfolio
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DESIGN: dracula
        ports:
            - 3000:8080
